### ISSUE TITLE
Add `with_label` to only add reviewers from a group if a label is present

### ISSUE THREAD

**Issue by uesteibar** [uesteibar/reviewer-lottery#15]
Something like:

```yaml
groups:
  - name: sample_group
    reviewers: 2
    with_label: sample-group-reviewers
    usernames:
      - user_a
      - user_b
      - user_c
```
