### ISSUE TITLE
Force pushing in a PR causes the workflow to pick a new reviewer from a team

### ISSUE THREAD

**Issue by CPerezz** [uesteibar/reviewer-lottery#26]
I think it should be mentioned somewhere that if the workflow is configured like:
```yaml
on:
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review]
```

The workflow internal logic is not prepared to re-select the same reviewer from a team and instead will assign a new one. Leading into PRs with multiple reviewers (depending on the amount of rebases and force-pushes done).

Should this be something that has to be avoided and we should config the workflow only like:
```yaml
on:
  pull_request:
    types: [opened]
```
Or should instead the logic of the tool be reworked when it comes to teams?
