### ISSUE TITLE
Feature - Avoid duplications of the selected reviewers

### ISSUE THREAD

**Issue by monorilaci** [uesteibar/reviewer-lottery#37]
We started to use this tool in our private repositories and we found that the tool can select the same person from the different groups.

I think it's a useful feature to avoid duplications of the selected reviewers.

For example, this is the definition of the groups:
```yaml
groups:
    - name: group_one
      reviewers: 1
      internal_reviewers: 1
      usernames:
        - person_one
        - person_two

    - name: group_two
      reviewers: 1
      internal_reviewers: 1
      usernames:
        - person_one
        - person_two
        - person_three
        - person_four
        - person_five
```
The tool can select the `person_one` user from the `group_one` and select the same user from the `group_two` and the consequence of it is that only 1 person is selected as a reviewer of the pull request instead of 2.

My suggested modifications in the [lottery.ts](https://github.com/uesteibar/reviewer-lottery/blob/master/src/lottery.ts) file:

First of all, change the 93rd line to this and concat the selected users with the author of the pull request:
```
            this.pickRandom(usernames, reviewersToRequest, selected.concat(author))
```
Second of all, change the 105th line to this because the type of the `ignore` parameter changed in the previous step:
```
  pickRandom(items: string[], n: number, ignore: string[]): string[] {
```
Finally, change the 108th line to avoid duplications:
```
    const candidates = items.filter(item => !ignore.includes(item));
```
