### ISSUE TITLE
Add `internal_reviewers` field to group

### ISSUE THREAD

**Issue by uesteibar** [uesteibar/reviewer-lottery#8]
It would be great to have an `internal_reviewers` group setting, that would set how many reviews are required from that group if the PR author belongs to it. Example:

For

```yaml
groups:
  - name: sample_group
    reviewers: 2
    internal_reviewers: 1
    usernames:
      - user_a
      - user_b
      - user_c
```

- If `user_a` opens a PR, then only one reviewer (either `user_b` or `user_c`) will be assigned
- If `user_d` opens a PR, then two reviewers from `sample_group` will be assigned

If `reviewers` is not added, then we should only set reviewers when a user within the team creates the PR.
